#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: linearregression-model
  namespace: oss
spec:
  annotations:
    seldon.io/istio-gateway: mesh
    seldon.io/istio-host: linearregression-model
  predictors:
    - name: main
      annotations:
        predictor_version: v1
        seldon.io/svc-name: linearregression-model
        prometheus.io/path: /prometheus
        prometheus.io/scrape: 'true'
      replicas: 1
      graph:
        name: model
        type: MODEL
        implementation: UNKNOWN_IMPLEMENTATION
        endpoint:
          type: "REST"
      componentSpecs:
        - spec:
            containers:
              - name: model
                image: appmgr.hart149-x2.ews.gic.ericsson.se/armdocker.rnd.ericsson.se/proj-smoke-dev/eric-oss-get-started-ml-model:0.0.6
      labels:
        sidecar.istio.io/inject: "true"
