#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-oss-get-started-ml-java-app.name" . }}-configmap
  labels:
  {{- include "eric-oss-get-started-ml-java-app.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-get-started-ml-java-app.annotations" . | nindent 4 }}
data:
  spring_kafka_bootstrap_servers: {{ template "eric-oss-get-started-ml-java-app.kafkaBootstrapServer" . }}
  spring_kafka_topics_input_name: {{ .Values.spring.kafka.topics.input.name | quote }}
  spring_kafka_topics_output_name: {{ .Values.spring.kafka.topics.output.name | quote }}
  spring_kafka_topics_output_partitions: {{ .Values.spring.kafka.topics.partitions | quote }}
  spring_kafka_topics_output_replicas: {{ .Values.spring.kafka.topics.replicas | quote }}
  spring_kafka_topics_output_retention_ms: {{ .Values.spring.kafka.topics.retention_ms | quote }}
  spring_kafka_topics_output_segment_in_bytes: {{ .Values.spring.kafka.topics.segment_in_bytes | quote }}
  spring_kafka_consumer_group_id: {{ .Values.spring.kafka.consumer.group_id | quote }}
  application.properties: |
    management.endpoint.metrics.enabled=true
    management.endpoints.web.exposure.include=*
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
    management.metrics.web.server.auto-time-requests=true