#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- $serviceMesh := include "eric-oss-get-started-ml-java-app.service-mesh-enabled" . | trim -}}
{{- $tls := include "eric-oss-get-started-ml-java-app.global-security-tls-enabled" . | trim -}}
{{- if and (eq $serviceMesh "true") (eq $tls "true") }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ include "eric-oss-get-started-ml-java-app.name" . }}-kafka-int-cert
  labels:
  {{- include "eric-oss-get-started-ml-java-app.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-get-started-ml-java-app.annotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ include "eric-oss-get-started-ml-java-app.name" . }}-kafka-secret
    certificateName: "cert.pem"
    privateKeyName: "key.pem"
  certificate:
    subject:
      cn: {{ include "eric-oss-get-started-ml-java-app.name" . }}
    issuer:
      reference: eric-oss-dmm-kf-op-sz-clients-ca-cert
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }}