#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if (.Values.apiGatewayRoute).routes }}
{{- $scheme := "http" }}
{{- $hosts := list .Values.global.hosts.gas }}
{{- range (.Values.apiGatewayRoute).routes }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-oss-get-started-ml-java-app-init.name" $ }}-{{ .id }}-route
  labels:
  {{- include "eric-oss-get-started-ml-java-app-init.labels" $ | nindent 4 }}
  annotations:
  {{- include "eric-oss-get-started-ml-java-app-init.annotations" $ | nindent 4 }}
data:
  route.json:
    {
      "id": "{{ include "eric-oss-get-started-ml-java-app-init.name" $ }}-{{ .id }}",
      "predicates": [
        {
          "name": "Path",
          "args": {
            "_genkey_0": "/seldon/{{ $.Release.Namespace }}/{{ .serviceName }}/**"
          }
        },
        {
          "name": "Host",
          "args": {
            {{- range $index, $host := $hosts }}
            {{- if ne $index 0 }},{{ end }}
            {{ printf "_genkey_%d" $index | quote }}: {{ $host | quote -}}
            {{- end }}
          }
        }
      ],
      "filters": [
        {
          "name": "AddRequestHeader",
          "args": {
            "_genkey_0": "X-RateLimit-Map-Name",
            "_genkey_1": "so-rate-limiter"
          }
        },
        {
          "name": "AddRequestHeader",
          "args": {
            "_genkey_0": "X-RateLimit-Max-Access",
            "_genkey_1": "410"
          }
        },
        {
          "name": "AddRequestHeader",
          "args": {
            "_genkey_0": "X-RateLimit-Reset-Time",
            "_genkey_1": "15"
          }
        },
        {
          "name": "RateLimitFilter",
          "args": {}
        },
        {
          "name": "AddUserNameCookieFilter",
          "args": {}
        }
      ],
      "uri": "{{$scheme}}://{{.serviceName}}:{{.port}}",
      "order": 0
    }
{{- end }}
{{- end }}