#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if (.Values.apiGatewayRoute).routes }}
{{- $scheme:= "https://" }}
{{- range (.Values.apiGatewayRoute).routes }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eric-oss-get-started-ml-java-app-init.name" $ }}-{{ .id }}-upgrade-route-hook
  labels:
    {{- include "eric-oss-get-started-ml-java-app-init.labels" $ | nindent 4 }}
  annotations:
    {{- include "eric-oss-get-started-ml-java-app-init.annotations" $ | nindent 4 }}
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
spec:
  backoffLimit: 8
  template:
    metadata:
      name: {{ include "eric-oss-get-started-ml-java-app-init.name" $ }}-upgrade-route-hook
      labels:
        {{- include "eric-oss-get-started-ml-java-app-init.labels" $ | nindent 8 }}
      annotations:
        {{- include "eric-oss-get-started-ml-java-app-init.annotations" $ | nindent 8 }}
    spec:
      serviceAccountName: eric-oss-get-started-ml-java-app
      {{- if include "eric-oss-get-started-ml-java-app-init.pullSecret" $ }}
      imagePullSecrets:
        - name: {{ include "eric-oss-get-started-ml-java-app-init.pullSecret" $ | quote }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: eric-api-gateway-client
          image: {{ include "eric-oss-get-started-ml-java-app-init.imagePath" (set $ "ImageKey" "eric-api-gateway-client") }}
          imagePullPolicy: {{ template "eric-oss-get-started-ml-java-app-init.registryImagePullPolicy" $ }}
          env:
            - name: SYSTEM_USER
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.apiGatewayRoute.credentials.name }}
                  key: {{ $.Values.apiGatewayRoute.credentials.userKey }}
            - name: SYSTEM_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.apiGatewayRoute.credentials.name }}
                  key: {{ $.Values.apiGatewayRoute.credentials.pwdKey }}
          args:
            - {{ .tag | quote }}
            - {{ printf "%s%s" $scheme $.Values.global.hosts.gas | quote }}
            - "$(SYSTEM_USER)"
            - "$(SYSTEM_USER_PASSWORD)"
            - "upgrade"
            - "/config/route.json"
          volumeMounts:
            - name: {{ .id }}-route-configuration-vol
              mountPath: /config
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: true
            runAsNonRoot: true
      {{- if (index $.Values "podPriority" "eric-oss-get-started-ml-java-app-init-create-user" "priorityClassName") }}
      priorityClassName: {{ (index $.Values "podPriority" "eric-oss-get-started-ml-java-app-init-create-user" "priorityClassName") }}
      {{- end }}
      {{- if $.Values.tolerations }}
      tolerations:
        {{- include "eric-oss-get-started-ml-java-app-init.tolerations" $ | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .id }}-route-configuration-vol
          configMap:
            name: {{ include "eric-oss-get-started-ml-java-app-init.name" $ }}-{{ .id }}-route
            defaultMode: 0440
      {{ include "eric-oss-get-started-ml-java-app-init.nodeSelector" $ | nindent 6 -}}
{{- end }}
{{- end }}